"""Apple Music cloud playlist creation and developer token extraction."""
from __future__ import annotations

import re
import time

from toolkit.core import APPLE_MUSIC_DEVELOPER_TOKEN, APPLE_MUSIC_USER_TOKEN, http_get, http_post
from toolkit.core.constants import (
    APPLE_MUSIC_API_CHUNK_SIZE,
    APPLE_MUSIC_API_RETRY_DELAY,
    MAX_RETRY_ATTEMPTS,
    TIMEOUT_API_LONG,
    TIMEOUT_API_SHORT,
    USER_AGENTS,
)
from toolkit.playlists.apple_music.state import CACHED_BEARER_TOKEN, console, logger


def get_apple_developer_token():
    """Dynamically extract Apple Music Web Developer Bearer Token using network HTTP helper."""
    if CACHED_BEARER_TOKEN[0]:
        return CACHED_BEARER_TOKEN[0]

    dev_env = APPLE_MUSIC_DEVELOPER_TOKEN
    if dev_env:
        CACHED_BEARER_TOKEN[0] = dev_env
        return dev_env

    try:
        url = "https://music.apple.com/assets/index~f0647adb63.js"
        res = http_get(url, headers={"User-Agent": USER_AGENTS[0]}, timeout=TIMEOUT_API_SHORT)
        tokens = re.findall(r"ey[A-Za-z0-9\-_=]{20,}\.ey[A-Za-z0-9\-_=]{20,}\.[A-Za-z0-9\-_=]{20,}", res.text)
        if tokens:
            CACHED_BEARER_TOKEN[0] = tokens[0]
            return tokens[0]
    except (OSError, ValueError) as e:
        logger.warning(f"Failed fetching Apple developer token: {e}")

    return None


def create_apple_music_cloud_playlist(playlist_name, tracks, user_token=None):
    """
    Directly create playlist in user's Apple Music Cloud account via official Apple Music API.
    Zero third-party website dependency! Uses 2-step batch chunking strategy with rate-limit delays.
    """
    u_token = user_token or APPLE_MUSIC_USER_TOKEN
    if not u_token:
        console.print(
            "[bold yellow]Notice: APPLE_MUSIC_USER_TOKEN not set in .env. Skipping direct Cloud"
            "Sync.[/bold yellow]"
        )
        return False

    dev_token = get_apple_developer_token()
    if not dev_token:
        console.print("[bold red]Error: Unable to fetch Apple Music developer token.[/bold red]")
        return False

    url_create = "https://amp-api.music.apple.com/v1/me/library/playlists"
    headers = {
        "Authorization": f"Bearer {dev_token}",
        "Music-User-Token": u_token,
        "Content-Type": "application/json",
        "Origin": "https://music.apple.com",
        "Referer": "https://music.apple.com/"
    }

    payload_create = {
        "attributes": {
            "name": playlist_name,
            "description": "Generated by Spotify - Apple Music Toolkit"
        }
    }

    try:
        resp = http_post(url_create, json=payload_create, headers=headers, timeout=TIMEOUT_API_LONG)
        if resp.status_code in [200, 201]:
            data = resp.json().get("data", [])
            if not data:
                console.print("[bold red]API Error:[/bold red] Could not parse created playlist ID.")
                return False

            playlist_id = data[0]["id"]
            console.print(f"[bold cyan]Playlist Container Created! (ID: {playlist_id})[/bold cyan]")

            track_ids = [item.get("trackId") for item in tracks if item.get("trackId")]
            all_track_objs = [{"id": str(tid), "type": "songs"} for tid in track_ids]

            url_add = f"https://amp-api.music.apple.com/v1/me/library/playlists/{playlist_id}/tracks"
            chunk_size = APPLE_MUSIC_API_CHUNK_SIZE
            added_count = 0

            for i in range(0, len(all_track_objs), chunk_size):
                chunk = all_track_objs[i : i + chunk_size]
                time.sleep(0.3)

                for attempt in range(MAX_RETRY_ATTEMPTS):
                    resp_add = http_post(url_add, json={"data": chunk}, headers=headers, timeout=TIMEOUT_API_LONG)
                    if resp_add.status_code in [200, 201, 204]:
                        added_count += len(chunk)
                        console.print(
                            f"[dim]Synced {added_count}/{len(all_track_objs)} tracks to Apple Music Cloud...[/dim]"
                        )
                        break
                    if resp_add.status_code == 429:
                        time.sleep(APPLE_MUSIC_API_RETRY_DELAY * (attempt + 1))
                    else:
                        console.print(
                            f"[bold yellow]Batch Add Notice "
                            f"({resp_add.status_code}):[/bold yellow] "
                            f"{resp_add.text[:150]}"
                        )
                        break

            console.print(
                f"[bold green]✓ SUCCESS! Playlist '{playlist_name}' "
                f"({added_count} tracks) synced directly to your "
                f"Apple Music Account![/bold green]"
            )
            return True
        console.print(f"[bold yellow]Apple Music API Notice ({resp.status_code}):[/bold yellow] {resp.text[:200]}")
    except (OSError, ValueError, KeyError) as e:
        logger.error(f"Apple Music cloud playlist API error: {e}")
        console.print(f"[bold red]API Exception:[/bold red] {e}")

    return False
