"""
Spotify Playlist Creator Module.
Converts text song lists into official Spotify playlists via Spotipy API.
Uses shared pre-sanitization, query generation, and strict candidate track verification.
"""

import os
import sys
import spotipy
from spotipy.oauth2 import SpotifyOAuth

from toolkit.core import (
    PLAYLIST_SOURCES_DIR,
    SPOTIPY_CLIENT_ID,
    SPOTIPY_CLIENT_SECRET,
    SPOTIPY_REDIRECT_URI,
    CACHE_DIR,
    get_network_session,
    ensure_all_folders,
)
from toolkit.playlists.parser import (
    parse_songs,
    scan_playlist_files,
    clean_string,
    pre_sanitize_song_line,
    generate_search_queries,
    verify_track_match,
)

from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.progress import Progress, SpinnerColumn, TextColumn, BarColumn, TaskProgressColumn
from rich.prompt import Prompt, Confirm

console = Console()
SCOPE = 'playlist-modify-public playlist-modify-private'
SOURCE_FOLDER_NAME = "playlist_sources"

def ensure_source_folder():
    """Ensure the playlist sources directory exists."""
    ensure_all_folders()

def get_spotify_client():
    """Authenticate and return Spotipy client instance with clean error handling."""
    if not SPOTIPY_CLIENT_ID or not SPOTIPY_CLIENT_SECRET or SPOTIPY_CLIENT_ID.startswith("your_"):
        console.print(Panel(
            "[bold red]SPOTIFY API CREDENTIALS REQUIRED[/bold red]\n\n"
            "[white]Missing or unconfigured SPOTIPY_CLIENT_ID / SPOTIPY_CLIENT_SECRET in your .env file.[/white]\n\n"
            "[bold yellow]How to fix:[/bold yellow]\n"
            "1. Visit [bold cyan]https://developer.spotify.com/dashboard[/bold cyan] and log in.\n"
            "2. Click [bold green]Create An App[/bold green], set App Name & Description.\n"
            "3. Add Redirect URI: [bold cyan]https://127.0.0.1:8888/callback[/bold cyan]\n"
            "4. Copy your [bold white]Client ID[/bold white] and [bold white]Client Secret[/bold white].\n"
            "5. Open your [bold magenta].env[/bold magenta] file and add:\n"
            "   [bold green]SPOTIPY_CLIENT_ID=your_actual_client_id[/bold green]\n"
            "   [bold green]SPOTIPY_CLIENT_SECRET=your_actual_client_secret[/bold green]",
            title="[bold yellow]Spotify Setup Instructions[/bold yellow]",
            border_style="red"
        ))
        return None
        
    try:
        session = get_network_session()
        auth_manager = SpotifyOAuth(
            client_id=SPOTIPY_CLIENT_ID,
            client_secret=SPOTIPY_CLIENT_SECRET,
            redirect_uri=SPOTIPY_REDIRECT_URI,
            scope=SCOPE,
            cache_path=os.path.join(CACHE_DIR, "spotify_token.json"),
            open_browser=True,
            requests_session=session
        )
        return spotipy.Spotify(auth_manager=auth_manager, requests_session=session)
    except Exception as e:
        console.print(Panel(
            f"[bold red]Spotify Authentication Error:[/bold red] {e}\n\n"
            "[yellow]Please check that your SPOTIPY_CLIENT_ID and SPOTIPY_CLIENT_SECRET in .env are correct.[/yellow]",
            title="[bold red]Authentication Failure[/bold red]",
            border_style="red"
        ))
        return None

def display_header(user_info=None):
    """Display clean application banner."""
    console.clear()
    user_str = f"[bold green]Account:[/bold green] {user_info['display_name']} ({user_info['id']})" if user_info else "[yellow]Authenticating...[/yellow]"
    
    banner_text = f"""[bold cyan]SPOTIFY PLAYLIST CREATOR[/bold cyan]
Convert text song lists into official Spotify playlists.
Folder: [bold magenta]{SOURCE_FOLDER_NAME}/[/bold magenta]
{user_str}"""
    console.print(Panel(banner_text, border_style="green", expand=False))

def search_track(sp, song_line):
    """
    Search for track on Spotify using multi-tier query strategy with strict candidate verification:
    1. Fielded query (track:Title artist:Artist)
    2. Clean query variations generated by generate_search_queries
    3. Strict verification (verify_track_match) to eliminate false artist/title substitutions.
    """
    queries = generate_search_queries(song_line)
    
    for query_text in queries:
        if ' - ' in query_text:
            parts = query_text.split(' - ', 1)
            title, artist = parts[0].strip(), parts[1].strip()
            sp_query = f"track:{title} artist:{artist}"
            try:
                results = sp.search(q=sp_query, limit=5, type='track')
                items = results.get('tracks', {}).get('items', [])
                for item in items:
                    cand_title = item.get('name', '')
                    cand_artist = item.get('artists', [{}])[0].get('name', '')
                    if verify_track_match(song_line, cand_title, cand_artist):
                        return item
            except Exception:
                pass
        
        try:
            results = sp.search(q=query_text, limit=5, type='track')
            items = results.get('tracks', {}).get('items', [])
            for item in items:
                cand_title = item.get('name', '')
                cand_artist = item.get('artists', [{}])[0].get('name', '')
                if verify_track_match(song_line, cand_title, cand_artist):
                    return item
        except Exception:
            pass

    return None

def import_file_to_spotify(sp, user_id, file_info, custom_name=None):
    """Process file and create Spotify playlist."""
    filename = file_info['filename']
    file_path = file_info['path']
    raw_songs = parse_songs(file_path)
    
    if not raw_songs:
        console.print(f"[bold yellow]Notice: '{filename}' contains no songs. Skipping.[/bold yellow]")
        return None

    cleaned_songs = [pre_sanitize_song_line(s) for s in raw_songs if pre_sanitize_song_line(s)]
    seen_keys = set()
    unique_songs = []
    for s in cleaned_songs:
        ckey = clean_string(s)
        if ckey and ckey not in seen_keys:
            seen_keys.add(ckey)
            unique_songs.append(s)

    playlist_name = custom_name or os.path.splitext(filename)[0].replace('_', ' ').title()

    console.print(f"\n[bold green]Creating Playlist:[/bold green] [bold white]{playlist_name}[/bold white] ({len(unique_songs)} unique songs)")
    
    track_uris = []
    not_found = []

    with Progress(
        SpinnerColumn(),
        TaskProgressColumn(),
        BarColumn(),
        TextColumn("[progress.description]{task.description}"),
        console=console
    ) as progress:
        task = progress.add_task("Searching Spotify...", total=len(unique_songs))
        
        for song in unique_songs:
            progress.update(task, description=f"Searching: [bold cyan]{song}[/bold cyan]")
            track = search_track(sp, song)
            if track:
                track_uris.append(track['uri'])
            else:
                not_found.append(song)
            progress.advance(task)

    if not track_uris:
        console.print(f"[bold red]Error: No matching songs found on Spotify for '{playlist_name}'.[/bold red]")
        return None

    playlist = sp.user_playlist_create(user=user_id, name=playlist_name, public=True)
    playlist_id = playlist['id']

    for i in range(0, len(track_uris), 100):
        batch = track_uris[i:i+100]
        sp.playlist_add_items(playlist_id, batch)

    table = Table(title=f"Summary: {playlist_name}", border_style="cyan")
    table.add_column("Property", style="bold white")
    table.add_column("Details", style="bold green")

    table.add_row("Total Listed Songs", str(len(unique_songs)))
    table.add_row("Added to Spotify", f"{len(track_uris)} ({int(len(track_uris)/len(unique_songs)*100)}%)")
    table.add_row("Unmatched Songs", str(len(not_found)))
    table.add_row("Playlist Web Link", f"[underline blue]{playlist['external_urls']['spotify']}[/underline blue]")

    console.print(table)

    if not_found:
        console.print(Panel(
            "\n".join([f"- {item}" for item in not_found[:15]]) + (f"\n... and {len(not_found)-15} more" if len(not_found) > 15 else ""),
            title=f"Unmatched Songs ({len(not_found)})",
            border_style="yellow"
        ))

    return playlist['external_urls']['spotify']

def list_files_table(file_info_list):
    """Display table of available playlist text files."""
    table = Table(title="Available Playlist Files", border_style="magenta", header_style="bold cyan")
    table.add_column("Index", style="bold yellow", justify="center")
    table.add_column("File Name", style="bold white")
    table.add_column("Song Count", justify="right", style="green")
    table.add_column("Size (KB)", justify="right", style="dim")

    for idx, info in enumerate(file_info_list, 1):
        size_kb = f"{info['size'] / 1024:.1f}"
        table.add_row(str(idx), info['filename'], str(info['song_count']), size_kb)

    console.print(table)

def interactive_menu(sp, user_info):
    """Run interactive menu loop."""
    user_id = user_info['id']

    while True:
        display_header(user_info)
        file_info_list = scan_playlist_files()

        console.print("[bold yellow]PLAYLIST CREATOR MENU:[/bold yellow]")
        console.print(" [bold cyan]1[/bold cyan] View Available Text Playlist Files")
        console.print(" [bold cyan]2[/bold cyan] Select One File to Create a Spotify Playlist")
        console.print(" [bold cyan]3[/bold cyan] Create Playlists for All Files (Batch Mode)")
        console.print(" [bold cyan]4[/bold cyan] User Guide")
        console.print(" [bold cyan]0[/bold cyan] Return to Main Menu")

        choice = Prompt.ask("\nSelect option", choices=["1", "2", "3", "4", "0"], default="1")

        if choice == "1":
            display_header(user_info)
            if not file_info_list:
                console.print(f"[bold yellow]No text files found in '{SOURCE_FOLDER_NAME}/'[/bold yellow]")
            else:
                list_files_table(file_info_list)
            Prompt.ask("\nPress Enter to return")

        elif choice == "2":
            display_header(user_info)
            if not file_info_list:
                console.print(f"[bold red]No text files found in '{SOURCE_FOLDER_NAME}/'.[/bold red]")
                Prompt.ask("\nPress Enter to return")
                continue

            list_files_table(file_info_list)
            valid_indices = [str(i) for i in range(1, len(file_info_list) + 1)]
            file_idx = Prompt.ask("\nSelect file index to import", choices=valid_indices)
            selected_file = file_info_list[int(file_idx) - 1]

            default_name = os.path.splitext(selected_file['filename'])[0].replace('_', ' ').title()
            custom_name = Prompt.ask("Spotify Playlist Name", default=default_name)

            import_file_to_spotify(sp, user_id, selected_file, custom_name=custom_name)
            Prompt.ask("\nPress Enter to return")

        elif choice == "3":
            display_header(user_info)
            if not file_info_list:
                console.print(f"[bold red]No text files found in '{SOURCE_FOLDER_NAME}/'.[/bold red]")
                Prompt.ask("\nPress Enter to return")
                continue

            list_files_table(file_info_list)
            if Confirm.ask(f"\nCreate Spotify playlists for all {len(file_info_list)} files?"):
                created_links = []
                for info in file_info_list:
                    link = import_file_to_spotify(sp, user_id, info)
                    if link:
                        created_links.append((info['filename'], link))
                
                if created_links:
                    console.print("\n[bold green]Batch Playlist Creation Complete![/bold green]")
                    for fname, link in created_links:
                        console.print(f"- [bold white]{fname}[/bold white]: [underline blue]{link}[/underline blue]")
            
            Prompt.ask("\nPress Enter to return")

        elif choice == "4":
            display_header(user_info)
            info_text = f"""[bold yellow]HOW TO USE PLAYLIST CREATOR[/bold yellow]

1. Place any text file (.txt) with song titles into:
   [bold magenta]{PLAYLIST_SOURCES_DIR}[/bold magenta]

2. Text File Format:
   Song Title - Artist Name  (or simply Song Title Artist Name)

3. The system will automatically search Spotify, create the playlist on your account,
   and output the direct link to listen!"""
            console.print(Panel(info_text, border_style="blue"))
            Prompt.ask("\nPress Enter to return")

        elif choice == "0":
            break

def main():
    ensure_source_folder()
    display_header()
    
    sp = get_spotify_client()
    if not sp:
        Prompt.ask("\nPress Enter to return to Main Menu")
        return
        
    try:
        user_info = sp.current_user()
        interactive_menu(sp, user_info)
    except (KeyboardInterrupt, EOFError):
        console.print("\n[bold yellow]Returning to Main Menu...[/bold yellow]")
        return
    except Exception as e:
        console.print(f"\n[bold red]Authentication Notice:[/bold red] {e}")
        console.print("[dim]Check your .env settings and ensure you clicked 'Save' in the Spotify Dashboard.[/dim]")
        Prompt.ask("\nPress Enter to return to Main Menu")
        return

if __name__ == '__main__':
    main()
